### ISSUE TITLE
UDP option?

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry/cf-drain-cli#5]
At the system level you can choose TCP or UDP for syslog. Is there an option for that with this plugin and the syslog adapter? We'd like to use UDP

**Comment by bradylove** [comment]
@bobbyhubbard The plugin and syslog adapter do not currently support UDP. 

@ahevenor (our PM) is currently on vacation but I will bring this up with him when he returns.

**Comment by bobbyhubbard** [comment]
Ok thanks for the info. It certainly would be a nice option.

**Comment by ahevenor** [comment]
@bobbyhubbard thanks for the feedback. There are some downsides to UDP (I am sure you are aware) but I don't see a reason we wouldn't support it. Technically the work will need to be done server side in [cf-syslog-drain](https://github.com/cloudfoundry/cf-syslog-drain-release) release though. I'll keep this issue for tracking though.

**Comment by bobbyhubbard** [comment]
Yeah in this case we were going to setup our nonprod foundation with udp. A few lost logs isn’t a huge deal in that case. ☺

**Comment by bradylove** [comment]
@ahevenor here is the spec for RFC 5424 over UDP https://tools.ietf.org/html/rfc5426

**Comment by jtuchscherer** [comment]
@bobbyhubbard 
We are going to put this on hold for now. If there is more widespread demand for syslog over UDP, we will gladly open this issue again and work on an implementation. 

I am closing this issue for now, but feel free to re-open it, if you feel like you absolutely need to have this feature in order to use CF.

Thanks
